apiVersion: v1
kind: Service
metadata:
  labels:
    app: proton-game-hermes
    game: Hermes
  name: proton-game-hermes
spec:
  type: LoadBalancer
  ports:
    - name: admin
      port: 80
      targetPort: 8080
    - name: player
      port: 10001
  selector:
    app: proton-game-hermes
